#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
    procd_open_instance "dsc-it100"
    procd_set_param command "/usr/bin/dsc-it100"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
