m = Map("security-event", translate("Event Settings"), translate(""))
d = m:section(TypedSection, "info", "")

a = d:option(Value, "500", "Command Acknowledge (500)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "501", "Command Error (501)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "502", "System Error (502)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "550", "Time/Date Broadcast (550)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "560", "Ring Detected (560)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "561", "Indoor Temperature Broadcast (561)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "562", "Outdoor Temperatrure Broadcast (562)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "563", "Thermostat Set Points (563)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "570", "Broadcast Labels (570)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "580", "Baud Rate Set (580)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "601", "Zone Alarm (601)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "602", "Zone Alarm Restore (602)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "603", "Zone Tamper (603)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "604", "Zone Tamper Restore (604)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "605", "Zone Fault (605)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "606", "Zone Fault Restore (606)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "609", "Zone Open (609)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "610", "Zone Restored (610)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "620", "Duress Alarm (620)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "621", "[F] Key Alarm (621)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "622", "[F] Key Restoral (622)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "623", "[A] Key Alarm (623)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "624", "[A] Key Restoral (624)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "625", "[P] Key Alarm (625)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "626", "[P] Key Restoral (626)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "631", "Auxiliary Input Alarm (631)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "632", "Auxiliary Input Alarm Restored (632)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "650", "Partition Ready (650)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "651", "Partition Not Ready (651)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "652", "Partition Armed - Descriptive Mode (652)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "653", "Partition in Ready to Force Arm (653)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "654", "Partition In Alarm (654)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "655", "Partition Disarmed (655)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "656", "Exit Delay in Progress (656)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "657", "Entry Delay in Progress (657)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "658", "Keypad Lock-out (658)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "659", "Keypad Blanking (659)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "660", "Command Output In Progress (660)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "670", "Invalid Access Code (670)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "671", "Function Not Available (671)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "672", "Fail to Arm (672)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "673", "Partition Busy (673)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "700", "User Closing (700)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "701", "Special Closing (701)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "702", "Partial Closing (702)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "750", "User Opening (750)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "751", "Special Opening (751)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "800", "Panel Battery Trouble (800)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "801", "Panel Battery Trouble Restore (801)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "802", "Panel AC Trouble (802)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "803", "Panel AC Restore (803)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "806", "System Bell Trouble (806)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "807", "System Bell Trouble Restoral (807)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "810", "TLM Line 1 Trouble (810)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "811", "TLM Line 1 Trouble Restored (811)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "812", "TLM Line 2 Trouble (812)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "813", "TLM Line 2 Trouble Restored (813)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "814", "FTC Trouble (814)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "816", "Buffer Near Full (816)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "821", "General Device Low Battery (821)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "822", "General Device Low Battery Restore (822)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "825", "Wireless Key Low Battery Trouble (825)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "826", "Wireless Key Low Battery Trouble Restore (826)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "827", "Handheld Keypad Low Battery Trouble (827)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "828", "Handheld Keypad Low Battery Restore Restored (828)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "829", "General System Tamper (829)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "830", "General System Tamper Restore (830)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "831", "Home Automation Trouble (831)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "832", "Home Automation Trouble Restore (832)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "840", "Trouble Status (LED ON) (840)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "841", "Trouble Status Restore (LED OFF) (841)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "842", "Fire Trouble Alarm (842)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "843", "Fire Trouble Alarm Restored (843)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "900", "Code Required (900)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "901", "LCD Update (901)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "902", "LCD Cursor (902)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "903", "LED Status (903)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "904", "Beep Status (904)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "905", "Tone Status (905)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "906", "Buzzer Status (906)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "907", "Door Chime Status (907)"); a.optional=false; a.rmempty = false;
a = d:option(Value, "908", "Software Version (908)"); a.optional=false; a.rmempty = false;

return m
